export type Category = 'Web' | 'Android' | 'Juegos' | 'Experimentos';
export type Project = { id: string; title: string; description: string; tech: string[]; repo?: string; category: Category; page?: string; note?: string; features?: string[]; featured?: boolean };
// Checked against public repository READMEs. No Android release assets are published.
export const projects: Project[] = [
  { id: 'dky', title: 'DKY Jewelry', category: 'Web', featured: true, description: 'Una tienda de joyería con catálogo dinámico, carrito y gestión de inventario. Del producto a la compra, con una experiencia pensada para móvil.', tech: ['JavaScript', 'HTML', 'CSS', 'Supabase'], repo: 'https://github.com/MrF3lipe/dky-jewelry', page: 'https://www.dkygold.com/', note: 'Una tienda real, un problema real.', features: ['Catálogo conectado a Supabase, con búsqueda y filtros.', 'Carrito y contacto por WhatsApp para consultas y ventas.', 'Panel de administración para gestionar el inventario.'] },
  { id: 'zofloridane', title: 'ZoFloridane', category: 'Web', featured: true, description: 'Una tienda online para comprar desde cualquier parte del mundo y entregar productos a tu familia en Cuba. Catálogo, carrito y seguimiento del pedido, con disponibilidad según la zona de entrega.', tech: ['Comercio electrónico', 'Catálogo', 'Pedidos'], page: 'https://zofloridane.com/', note: 'Un puente para estar cerca, incluso desde lejos.', features: ['Catálogo de alimentos, bebidas, aseo y productos para el hogar.', 'Selección de localidad y disponibilidad para el destino.', 'Carrito, seguimiento de pedidos y atención por WhatsApp.'] },
  { id: 'kitchen', title: 'Kitchen Cabinet', category: 'Android', featured: true, description: 'Recetas, despensa, compras y planificación semanal en una aplicación Android nativa. Una pequeña ayuda para organizar lo que pasa en la cocina.', tech: ['Kotlin', 'Jetpack Compose', 'Room'], repo: 'https://github.com/MrF3lipe/KC-Kotlin', note: 'Menos «¿qué cocino hoy?», más organización.', features: ['Recetario con categorías, favoritos y búsqueda por ingredientes.', 'Despensa, lista de la compra y planificación semanal.', 'Modo cocina paso a paso, temporizador y ajustes de porciones.'] },
  { id: 'gastos', title: 'Gastos Miniapp', category: 'Web', description: 'Una miniapp de Telegram para registrar gastos e ingresos, organizar movimientos y consultar presupuestos.', tech: ['HTML', 'JavaScript', 'Telegram'], repo: 'https://github.com/MrF3lipe/gastos-miniapp' },
  { id: 'domino', title: 'Domino Game', category: 'Juegos', description: 'Dominó en Godot con inteligencia artificial y cuatro niveles de dificultad.', tech: ['Godot', 'GDScript'], repo: 'https://github.com/MrF3lipe/Domino-Game' },
  { id: 'torneo', title: 'Torneo de Subagentes', category: 'Experimentos', description: 'Un experimento: siete agentes de IA, setenta páginas web y distintas formas de resolver el mismo reto.', tech: ['HTML', 'IA'], repo: 'https://github.com/MrF3lipe/torneo-subagentes', page: 'https://mrf3lipe.github.io/torneo-subagentes/' },
  { id: 'test', title: 'Kitchen Cabinet Lab', category: 'Android', description: 'El cuaderno de pruebas de Kitchen Cabinet: componentes, arquitectura y nuevas funciones antes de llevarlas a la app principal.', tech: ['Kotlin', 'Jetpack Compose', 'Room'], repo: 'https://github.com/MrF3lipe/test' },
  { id: 'portfolio', title: 'Este cuaderno', category: 'Web', description: 'Mi portfolio personal. Mis proyectos, las herramientas que uso y mi manera de construir.', tech: ['React', 'TypeScript', 'CSS'], repo: 'https://github.com/MrF3lipe/MrF3lipe' },
];
