import type { Variant } from './SketchBuild';

export type Category = 'Web' | 'Android' | 'Juegos' | 'Experimentos';
/** The project's English copy; whatever it leaves out is shown as written. */
export type ProjectCopy = { description: string; kicker?: string; tech?: string[]; note?: string; features?: string[] };
export type Project = { id: string; title: string; kicker?: string; variant?: Variant; description: string; tech: string[]; repo?: string; category: Category; page?: string; note?: string; features?: string[]; featured?: boolean; en?: ProjectCopy };
// Checked against public repository READMEs. No Android release assets are published.
export const projects: Project[] = [
  { id: 'dky', title: 'DKY Jewelry', category: 'Web', featured: true, description: 'Una tienda de joyería con catálogo dinámico, carrito y gestión de inventario. Del producto a la compra, con una experiencia pensada para móvil.', tech: ['JavaScript', 'HTML', 'CSS', 'Supabase'], repo: 'https://github.com/MrF3lipe/dky-jewelry', page: 'https://www.dkygold.com/', note: 'Una tienda real, un problema real.', features: ['Catálogo conectado a Supabase, con búsqueda y filtros.', 'Carrito y contacto por WhatsApp para consultas y ventas.', 'Panel de administración para gestionar el inventario.'], en: { description: 'A jewelry store with a dynamic catalog, cart and inventory management. From product to purchase, with an experience designed for mobile.', note: 'A real store, a real problem.', features: ['Catalog connected to Supabase, with search and filters.', 'Cart, plus WhatsApp contact for questions and sales.', 'Admin panel to manage the inventory.'] } },
  { id: 'zofloridane', title: 'ZoFloridane', category: 'Web', featured: true, variant: { scene: 'zofloridane-app', label: 'app', back: 'web', to: 'phone', app: true }, description: 'Una tienda online para comprar desde cualquier parte del mundo y entregar productos a tu familia en Cuba. Catálogo, carrito y seguimiento del pedido, con disponibilidad según la zona de entrega.', tech: ['Comercio electrónico', 'Catálogo', 'Pedidos'], page: 'https://zofloridane.com/', note: 'Un puente para estar cerca, incluso desde lejos.', features: ['Catálogo de alimentos, bebidas, aseo y productos para el hogar.', 'Selección de localidad y disponibilidad para el destino.', 'Carrito, seguimiento de pedidos y atención por WhatsApp.'], en: { description: 'An online store to shop from anywhere in the world and deliver products to your family in Cuba. Catalog, cart and order tracking, with availability based on the delivery area.', tech: ['E-commerce', 'Catalog', 'Orders'], note: 'A bridge to stay close, even from far away.', features: ['Catalog of food, drinks, toiletries and household products.', 'Choose the locality and see availability at the destination.', 'Cart, order tracking and support over WhatsApp.'] } },
  { id: 'kitchen', title: 'Kitchen Cabinet', category: 'Android', featured: true, description: 'Recetas, despensa, compras y planificación semanal en una aplicación Android nativa. Una pequeña ayuda para organizar lo que pasa en la cocina.', tech: ['React', 'TanStack', 'Capacitor', 'PHP'], note: 'Menos «¿qué cocino hoy?», más organización.', features: ['Recetario con categorías, favoritos y búsqueda por ingredientes.', 'Despensa, lista de la compra y planificación semanal.', 'Modo cocina paso a paso, temporizador y ajustes de porciones.'], en: { description: 'Recipes, pantry, shopping and weekly planning in a native Android app. A little help to organize what happens in the kitchen.', note: 'Less “what should I cook today?”, more organization.', features: ['Recipe book with categories, favorites and search by ingredient.', 'Pantry, shopping list and weekly planning.', 'Step-by-step cooking mode, timer and portion adjustments.'] } },
  { id: 'glamour', title: 'The Glamour', category: 'Web', featured: true, kicker: 'reservas sin llamadas', variant: { scene: 'glamour-web', label: 'web', back: 'móvil', to: 'desktop' }, description: 'Reservas online para un salón de uñas en Sarasota, Florida. La clienta elige servicio, día y hora, y aparta su cita con un depósito; la dueña la confirma desde su propio panel.', tech: ['PHP', 'MySQL', 'JavaScript'], note: 'Menos mensajes, más citas.', features: ['Servicios por categoría, con foto, duración, precio y depósito.', 'Calendario con horarios libres según su semana y sus días cerrados.', 'Panel para confirmar depósitos y recordatorios por correo un día antes.'], en: { kicker: 'bookings without calls', description: 'Online booking for a nail salon in Sarasota, Florida. The client picks a service, day and time, and holds her appointment with a deposit; the owner confirms it from her own dashboard.', note: 'Fewer messages, more appointments.', features: ['Services by category, with photo, duration, price and deposit.', 'Calendar with open slots based on her week and her days off.', 'Dashboard to confirm deposits, and email reminders the day before.'] } },
  { id: 'gastos', title: 'Gastos Miniapp', category: 'Web', description: 'Una miniapp de Telegram para registrar gastos e ingresos, organizar movimientos y consultar presupuestos.', tech: ['HTML', 'JavaScript', 'Telegram'], repo: 'https://github.com/MrF3lipe/gastos-miniapp' },
  { id: 'domino', title: 'Domino Game', category: 'Juegos', description: 'Dominó en Godot con inteligencia artificial y cuatro niveles de dificultad.', tech: ['Godot', 'GDScript'], repo: 'https://github.com/MrF3lipe/Domino-Game' },
  { id: 'torneo', title: 'Torneo de Subagentes', category: 'Experimentos', description: 'Un experimento: siete agentes de IA, setenta páginas web y distintas formas de resolver el mismo reto.', tech: ['HTML', 'IA'], repo: 'https://github.com/MrF3lipe/torneo-subagentes', page: 'https://mrf3lipe.github.io/torneo-subagentes/' },
  { id: 'test', title: 'Kitchen Cabinet Lab', category: 'Android', description: 'El cuaderno de pruebas de Kitchen Cabinet: componentes, arquitectura y nuevas funciones antes de llevarlas a la app principal.', tech: ['Kotlin', 'Jetpack Compose', 'Room'], repo: 'https://github.com/MrF3lipe/test' },
  { id: 'portfolio', title: 'Este cuaderno', category: 'Web', description: 'Mi portfolio personal. Mis proyectos, las herramientas que uso y mi manera de construir.', tech: ['React', 'TypeScript', 'CSS'], repo: 'https://github.com/MrF3lipe/MrF3lipe' },
];
